services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dockerdb'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
volumes:
  postgres_data:
    driver: local