networks:
  dev-network:
    driver: bridge

services:
  grafana:
    image: 'grafana/grafana:latest'
    ports:
      - '3000:3000'
    networks:
      - 'dev-network'
  prometheus:
    image: 'prom/prometheus:latest'
    volumes:
      - './config/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus_data:/prometheus'
    ports:
      - '9090:9090'
    networks:
      - 'dev-network'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dockerdb'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
volumes:
  prometheus_data:
  grafana_data:
  postgres_data:
    driver: local